# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/demo1
spring.datasource.username=root
spring.datasource.password=123456@Abc

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Server
server.port=8080

# password
spring.security.user.name=Tinguyen
spring.security.user.password=317058

# config view engine
# spring.mvc.view.prefix=/WEB-INF/view/
# spring.mvc.view.suffix=.jsp
